// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5n4OeBno3-SIIvfqMschK_SyFgZPJaL8',
    appId: '1:126803614927:web:1f6a04e25357774a99ebba',
    messagingSenderId: '126803614927',
    projectId: 'social-connectify-my',
    authDomain: 'social-connectify-my.firebaseapp.com',
    storageBucket: 'social-connectify-my.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuQS4TWsCKhey00bRxiUch1vKLSWbZZBA',
    appId: '1:126803614927:android:14d109dec6650b3b99ebba',
    messagingSenderId: '126803614927',
    projectId: 'social-connectify-my',
    storageBucket: 'social-connectify-my.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgRXWkuPR3nGNlxON5FvD1XHuDKEwMxSk',
    appId: '1:126803614927:ios:cf1325eda1b410e899ebba',
    messagingSenderId: '126803614927',
    projectId: 'social-connectify-my',
    storageBucket: 'social-connectify-my.firebasestorage.app',
    iosBundleId: 'com.example.connectify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgRXWkuPR3nGNlxON5FvD1XHuDKEwMxSk',
    appId: '1:126803614927:ios:cf1325eda1b410e899ebba',
    messagingSenderId: '126803614927',
    projectId: 'social-connectify-my',
    storageBucket: 'social-connectify-my.firebasestorage.app',
    iosBundleId: 'com.example.connectify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5n4OeBno3-SIIvfqMschK_SyFgZPJaL8',
    appId: '1:126803614927:web:c408687932e0c2a499ebba',
    messagingSenderId: '126803614927',
    projectId: 'social-connectify-my',
    authDomain: 'social-connectify-my.firebaseapp.com',
    storageBucket: 'social-connectify-my.firebasestorage.app',
  );
}
